[book]
authors = ["layerhouse contributors"]
language = "en"
src = "src"
title = "layerhouse Documentation"

[build]
create-missing = true

[output.html]
edit-url-template = "https://github.com/layerhouse-oci/layerhouse/edit/main/docs/mdbook/{path}"
git-repository-url = "https://github.com/layerhouse-oci/layerhouse"

[preprocessor.mermaid]
command = "mdbook-mermaid"
