storage:
  s3:
    endpoint: http://s3.example.internal:9000
    bucket: layerhouse

certManager:
  server:
    enabled: true
    issuerRef:
      name: letsencrypt-prod
      kind: ClusterIssuer
      group: cert-manager.io
  raft:
    enabled: true
    issuerRef:
      name: layerhouse-raft-ca
      kind: Issuer
      group: cert-manager.io

server:
  tls:
    dnsNames:
      - registry.example.internal
      - layerhouse-nodeport.example.internal
